# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ["Launcher.py", "MainWindow.py", "Difficulty_ScoreAnalyze.py", "HitDelay.py",
        "MusyncSavDecode.py", "Resources.py", "Toolkit.py"],
    pathex=["F:\Files\Project_File\Program_Project\Python\MUSYNCSavDecode"],
    binaries=[],
    datas=[],
    hiddenimports=["MainWindow", "Difficulty_ScoreAnalyze", "HitDelay", "MusyncSavDecode", "Resources", "Toolkit"],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

WithConsole = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='MusyncSaveDecodeCLI',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['musync_data\\Musync.ico'],
)
WithConsoleColl = COLLECT(
    WithConsole,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='MusyncSaveDecodeCLI',
)

WithConsoleAllInOne = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    exclude_binaries=False,
    name='MusyncSaveDecodeCLI',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['musync_data\\Musync.ico'],
)

WithoutConsole = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='MusyncSaveDecodeNoCLI',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['musync_data\\Musync.ico'],
)
WithoutConsoleColl = COLLECT(
    WithoutConsole,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='MusyncSaveDecodeNoCLI',
)

WithoutConsoleAllInOne = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    exclude_binaries=False,
    name='MusyncSaveDecodeNoCLI',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['musync_data\\Musync.ico'],
)
