name: Auto Push Pre-Release Build
on:
  push:
    branches:
      - 'dev'   # 纯粹监听 dev 分支的直接推送

permissions:
  contents: write

env:
  RCVersion: < 0.0.0 PreRelease 0>
  isPreRelease: true
  Version: Init

jobs:
  Build_Push_PreRelease:
    name: Build Push PreRelease Application
    runs-on: windows-2025
    steps:
      - name: CheckOut Repo
        uses: actions/checkout@v4

      - name: Cache and Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.5'
          cache: 'pip'

      - name: Install requirements
        run: pip3 install -r ./requirements.txt

      # 把本次 Push 的最新 Commit 作为标题提取
      - name: Resolve Push Title
        run: |
          # 提取多行 Commit 信息的首行作为发布标题
          $TITLE = "${{ github.event.head_commit.message }}" -split "`n" | Select-Object -First 1
          Write-Host "Resolved Title: $TITLE"
          echo "RELEASE_TITLE=$TITLE" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Hardcode Release Type (Pre-Release)
        run: |
          $versionPath = "./musync_save/version.py"
          $content = Get-Content -Path $versionPath -Raw
          # 升级版正则：强制设为 True
          $content = $content -replace '(?m)^is_pre_release\s*(:\s*bool\s*)?=\s*(True|False)', 'is_pre_release: bool = True'
          Set-Content -Path $versionPath -Value $content -Encoding utf8
          Write-Host "已将 version.py 中的 is_pre_release 强制设置为 True (预发布版)"

      - name: Create Build Variable
        run: |
          $ErrorActionPreference = 'Stop';
          cd ./musync_save/;
          $isPreRelease = python -c "import version;print(version.is_pre_release)";
          $isPreReleaseBool = [bool]::Parse($isPreRelease);
          if ($isPreReleaseBool) {
              $version = python -c "import version; print(version.pre_version)";
              $rcVersion = $version -replace "pre", " PreRelease ";
          } else {
              $version = python -c "import version; print(version.version)";
              $rcVersion = $version + " Release";
          }
          echo "v:'${version}',rcv:'${rcVersion}'";
          echo "isPreRelease=${isPreReleaseBool}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append;
          echo "Version=${version}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append;
          echo "RCVersion=< ${rcVersion} >" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append;

      - name: Build ${{ env.Version }}
        run: pwsh ./buildLauncher.ps1;

      - name: Commit Pre-Release File
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          name: ${{ env.RCVersion }}  ${{ env.RELEASE_TITLE }}  < Auto Push Pre-Release >
          tag_name: ${{ env.Version }}
          draft: false
          prerelease: ${{ env.isPreRelease }} # 强制锁定为预发布
          generate_release_notes: true # GitHub 的自动日志比对功能
          files: ./MusyncSaveDecode/Archive/*
